org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Project
project_group=net.momirealms
project_version=26.7.1

# Common
latest_minecraft_version=26.2
min_supported_minecraft_version=26.2
cloth_version=26.2.155

# Fabric
fabric_version=0.154.2+26.2
loader_version=0.19.3
modmenu_version=20.0.0